import { Brand } from "@askua/core/brand";

/**
 * ```ts
 * const u8: U8 = 0;
 * ```
 */
export type U8 = number;

/**
 * ```ts
 * const u32: U32 = 0;
 * ```
 */
export type U32 = number;

/**
 * ```ts
 * const u64: U64 = 0n;
 * ```
 */
export type U64 = bigint;

/**
 * ```ts
 * const ptr: Pointer<U8> = 0;
 * ```
 */
export type Pointer<_> = number;

export class Exit extends Error {
  constructor(readonly code: Exitcode) {
    super(`Exit ${code}`);
  }
}

/**
 * ```ts
 * const size: Size = Size(0);
 * ```
 */
export type Size = Brand<U32, "wasi_snapshot_preview1.size">;
export const Size = Brand<U32, "wasi_snapshot_preview1.size">;

const timestamp = (u64: U64) =>
  Brand<U64, "wasi_snapshot_preview1.timestamp">(u64);

/**
 * timestamp: u64
 *
 * Timestamp in nanoseconds.
 *
 * - Size: 8
 * - Alignment: 8
 */
export type Timestamp = Brand<U64, "wasi_snapshot_preview1.timestamp">;
export const Timestamp = Object.assign(
  timestamp,
  {
    /**
     * Clockid.realtime
     */
    realtime(): Timestamp {
      return timestamp(BigInt(new Date().getTime()) * 1_000_000n);
    },
    /**
     * Clockid.monotonic
     */
    monotonic(): Timestamp {
      return timestamp(BigInt(Math.floor(performance.now() * 1_000_000)));
    },
  },
);

const clockid = (id: number) =>
  Brand<number, "wasi_snapshot_preview1.clockid">(id);

/**
 * clockid: Variant
 *
 * Identifiers for clocks.
 */
export type Clockid = Brand<number, "wasi_snapshot_preview1.clockid">;
export const Clockid = Object.assign(
  clockid,
  {
    /**
     * The clock measuring real time. Time value zero corresponds with
     * 1970-01-01T00:00:00Z.
     */
    realtime: clockid(0),

    /**
     * The store-wide monotonic clock, which is defined as a clock measuring
     * real time, whose value cannot be adjusted and which cannot have negative
     * clock jumps. The epoch of this clock is undefined. The absolute time
     * value of this clock therefore has no meaning.
     */
    monotonic: clockid(1),

    /**
     * The CPU-time clock associated with the current process.
     */
    process_cputime_id: clockid(2),

    /**
     * The CPU-time clock associated with the current thread.
     */
    thread_cputime_id: clockid(3),
  },
);

/**
 * Exit code generated by a process when exiting.
 *
 * - Size: 4
 * - Alignment: 4
 */
export type Exitcode = Brand<U32, "wasi_snapshot_preview1.exitcode">;

/**
 * ```ts
 * const code: Exitcode = Exitcode(0);
 * ```
 */
export const Exitcode = Brand<number, "wasi_snapshot_preview1.exitcode">;

const errno = (n: number) => Brand<number, "wasi_snapshot_preview1.errno">(n);

/**
 * errno: Variant
 *
 * Error codes returned by functions. Not all of these error codes are returned
 * by the functions provided by this API; some are used in higher-level library
 * layers, and others are provided merely for alignment with POSIX.
 */
export type Errno = Brand<number, "wasi_snapshot_preview1.errno">;
export const Errno = Object.assign(
  errno,
  {
    // No error occurred. System call completed successfully.
    success: errno(0),

    // Argument list too long.
    toobig: errno(1),

    // Permission denied.
    acces: errno(2),

    // Address in use.
    addrinuse: errno(3),

    // Address not available.
    addrnotavail: errno(4),

    // Address family not supported.
    afnosupport: errno(5),

    // Resource unavailable, or operation would block.
    again: errno(6),

    // Connection already in progress.
    already: errno(7),

    // Bad file descriptor.
    badf: errno(8),

    // Bad message.
    badmsg: errno(9),

    // Device or resource busy.
    busy: errno(0),

    // Operation canceled.
    canceled: errno(1),

    // No child processes.
    child: errno(2),

    // Connection aborted.
    connaborted: errno(3),

    // connrefused Connection refused.
    connrefused: errno(4),

    // connreset Connection reset.
    connreset: errno(5),

    // Resource deadlock would occur.
    deadlk: errno(6),

    // Destination address required.
    destaddrreq: errno(7),

    // Mathematics argument out of domain of function.
    dom: errno(8),

    // Reserved.
    dquot: errno(9),

    // File exists.
    exist: errno(0),

    // Bad address.
    fault: errno(1),

    // File too large.
    fbig: errno(2),

    // Host is unreachable.
    hostunreach: errno(3),

    // Identifier removed.
    idrm: errno(4),

    // Illegal byte sequence.
    ilseq: errno(5),

    // Operation in progress.
    inprogress: errno(6),

    // Interrupted function.
    intr: errno(7),

    // Invalid argument.
    inval: errno(8),

    // I/O error.
    io: errno(9),

    // Socket is connected.
    isconn: errno(0),

    // Is a directory.
    isdir: errno(1),

    // Too many levels of symbolic links.
    loop: errno(2),

    // File descriptor value too large.
    mfile: errno(3),

    // Too many links.
    mlink: errno(4),

    // Message too large.
    msgsize: errno(5),

    // Reserved.
    multihop: errno(6),

    // Filename too long.
    nametoolong: errno(7),

    // Network is down.
    netdown: errno(8),

    // Connection aborted by network.
    netreset: errno(9),

    // Network unreachable.
    netunreach: errno(0),

    // Too many files open in system.
    nfile: errno(1),

    // No buffer space available.
    nobufs: errno(2),

    // No such device.
    nodev: errno(3),

    // No such file or directory.
    noent: errno(4),

    // Executable file format error.
    noexec: errno(5),

    // No locks available.
    nolck: errno(6),

    // Reserved.
    nolink: errno(7),

    // Not enough space.
    nomem: errno(8),

    // No message of the desired type.
    nomsg: errno(9),

    // Protocol not available.
    noprotoopt: errno(0),

    // No space left on device.
    nospc: errno(1),

    // Function not supported.
    nosys: errno(2),

    // The socket is not connected.
    notconn: errno(3),

    // Not a directory or a symbolic link to a directory.
    notdir: errno(4),

    // Directory not empty.
    notempty: errno(5),

    // State not recoverable.
    Notrecoverable: errno(6),

    // Not a socket.
    notsock: errno(7),

    // Not supported, or operation not supported on socket.
    notsup: errno(8),

    // Inappropriate I/O control operation.
    notty: errno(9),

    // No such device or address.
    nxio: errno(0),

    // Value too large to be stored in data type.
    overflow: errno(1),

    // Previous owner died.
    ownerdead: errno(2),

    // Operation not permitted.
    perm: errno(3),

    // Broken pipe.
    pipe: errno(4),

    // Protocol error.
    proto: errno(5),

    // Protocol not supported.
    protonosupport: errno(6),

    // Protocol wrong type for socket.
    prototypes: errno(7),

    // Result too large.
    range: errno(8),

    // Read-only file system.
    rofs: errno(9),

    // Invalid seek.
    spipe: errno(0),

    // No such process.
    srch: errno(1),

    // Reserved.
    stale: errno(2),

    // Connection timed out.
    timedout: errno(3),

    // Text file busy.
    txtbsy: errno(4),

    // Cross-device link.
    xdev: errno(5),

    // Extension: Capabilities insufficient.
    notcapable: errno(6),
  },
);

/**
 * fd: Handle
 *
 * A file descriptor handle.
 */
export type Fd = Brand<number, "wasi_snapshot_preview1.fd">;
export const Fd = Brand<number, "wasi_snapshot_preview1.fd">;

/**
 * ciovec: Record
 *
 * A region of memory for scatter/gather writes.
 *
 * - Size: 8
 * - Alignment: 4
 *
 * ## Record members
 *
 * - buf: ConstPointer<u8> The address of the buffer to be written.
 *   - Offset: 0
 * - buf_len: size The length of the buffer to be written.
 *   - Offset: 4
 */
export type Ciovec = Brand<never, "wasi_snapshot_preview1.ciovec">;

/**
 * subscription: Record
 *
 * Subscription to an event.
 *
 * - Size: 48
 * - Alignment: 8
 *
 * ## Record members
 *
 * - userdata: [userdata] User-provided value that is attached to the
 *   subscription in the implementation and returned through [event::userdata].
 *   - Offset: 0
 * - u: [subscription_u] The type of the event to which to subscribe, and its
 *   contents
 *   - Offset: 8
 */
export type Subscription = Brand<never, "wasi_snapshot_preview1.subscription">;

/**
 * event: Record
 *
 * An event that occurred.
 *
 * - Size: 32
 * - Alignment: 8
 *
 * ## Record members
 *
 * - userdata: userdata User-provided value that got attached to
 *   subscription::userdata.
 *   - Offset: 0
 * - error: errno If non-zero, an error that occurred while processing the
 *   subscription request.
 *   - Offset: 8
 * - type: eventtype The type of event that occured
 *   - Offset: 10
 * - fd_readwrite: event_fd_readwrite The contents of the event, if it is an
 *   eventtype::fd_read or eventtype::fd_write. eventtype::clock events ignore this field.
 *   - Offset: 16
 */
export type Event = Brand<never, "wasi_snapshot_preview1.event">;

const fdflags = (flag: number) =>
  Brand<number, "wasi_snapshot_preview1.fdflags">(flag);

/**
 * fdflags: Record
 *
 * File descriptor flags.
 *
 * - Size: 2
 * - Alignment: 2
 */
export type Fdflags = Brand<number, "wasi_snapshot_preview1.fdflags">;
export const Fdflags = Object.assign(
  fdflags,
  {
    /**
     * bool Append mode: Data written to the file is always appended to
     * the file's end.
     *
     * - Bit: 0
     */
    append: fdflags(1),

    /**
     * bool Write according to synchronized I/O data integrity
     * completion. Only the data stored in the file is synchronized.
     *
     * - Bit: 1
     */
    dsync: fdflags(2),

    /**
     * bool Non-blocking mode.
     *
     * - Bit: 2
     */
    nonblock: fdflags(4),

    /**
     * bool Synchronized read I/O operations.
     *
     * - Bit: 3
     */
    rsync: fdflags(8),

    /**
     * bool Write according to synchronized I/O file integrity completion.
     * In addition to synchronizing the data stored in the file, the
     * implementation may also synchronously update the file's metadata.
     *
     * - Bit: 4
     */
    sync: fdflags(16),

    toString(f: Fdflags): string {
      return [
        `append:${f & Fdflags.append}`,
        `dsync:${f & Fdflags.dsync}`,
        `nonblock:${f & Fdflags.nonblock}`,
        `rsync:${f & Fdflags.rsync}`,
        `sync:${f & Fdflags.sync}`,
      ].join(", ");
    },
  },
);

/**
 * fdstat: Record
 *
 * File descriptor attributes.
 *
 * - Size: 24
 * - Alignment: 8
 *
 * ## Record members
 *
 * - fs_filetype: filetype File type.
 *   - Offset: 0
 * - fs_flags: fdflags File descriptor flags.
 *   - Offset: 2
 * - fs_rights_base: rights Rights that apply to this file descriptor.
 *   - Offset: 8
 * - fs_rights_inheriting: rights Maximum set of rights that may be installed on
 *   new file descriptors that are created through this file descriptor, e.g.,
 *   through path_open.
 *   - Offset: 16
 */
export type Fdstat = Brand<never, "wasi_snapshot_preview1.fdstat">;
export const Fdstat = {
  size: 24,
  fs_filetype_set(memory: DataView, filetype: Filetype): void {
    memory.setUint16(0, filetype, true);
  },

  fs_flags_set(memory: DataView, fdflags: Fdflags): void {
    memory.setUint16(2, fdflags, true);
  },

  fs_rights_base_set(memory: DataView, rights: Rights): void {
    memory.setBigInt64(8, rights, true);
  },

  fs_rights_inheriting_set(memory: DataView, rights: Rights): void {
    memory.setBigInt64(16, rights, true);
  },
};

/**
 * prestat: Variant
 *
 * Information about a pre-opened capability.
 *
 * - Size: 8
 * - Alignment: 4
 *
 * ## Variant Layout
 *
 * - size: 8
 * - align: 4
 * - tag_size: 1
 *
 * ## Variant cases
 *
 * - dir: prestat_dir
 */
export type Prestat = Brand<never, "wasi_snapshot_preview1.prestat">;

const filetype = Brand<number, "wasi_snapshot_preview1.filetype">;

/**
 * filetype: Variant
 *
 * The type of a file descriptor or file.
 *
 * - Size: 1
 * - Alignment: 1
 */
export type Filetype = Brand<number, "wasi_snapshot_preview1.filetype">;
export const Filetype = Object.assign(
  (n: number) => filetype(n),
  {
    /**
     * The type of the file descriptor or file is unknown or is different from
     * any of the other types specified.
     */
    unknown: filetype(0 as const),

    /**
     * The file descriptor or file refers to a block device inode.
     */
    block_device: filetype(1),

    /**
     * The file descriptor or file refers to a character device inode.
     */
    character_device: filetype(2),

    /**
     * The file descriptor or file refers to a directory inode.
     */
    directory: filetype(3),

    /**
     * The file descriptor or file refers to a regular file inode.
     */
    regular_file: filetype(4),

    /**
     * The file descriptor or file refers to a datagram socket.
     */
    socket_dgram: filetype(5),

    /**
     * The file descriptor or file refers to a byte-stream socket.
     */
    socket_stream: filetype(6),

    /**
     * The file refers to a symbolic link inode.
     */
    symbolic_link: filetype(7),
  },
);

const rights = Brand<U64, "wasi_snapshot_preview1.rights">;

/**
 * rights: Record
 *
 * File descriptor rights, determining which actions may be performed.
 *
 * - Size: 8
 * - Alignment: 8
 */
export type Rights = Brand<U64, "wasi_snapshot_preview1.rights">;
export const Rights = Object.assign(
  (n: bigint) => rights(n),
  {
    /**
     * The right to invoke `fd_datasync`. If `path_open` is set, includes the
     * right to invoke path_open with fdflags::dsync.
     *
     * - Bit: 0
     */
    fd_datasync: rights(1n << 0n),

    /**
     * The right to invoke `fd_read` and `sock_recv`. If `rights::fd_seek` is
     * set, includes the right to invoke `fd_pread`.
     *
     * - Bit: 1
     */
    fd_read: rights(1n << 1n),

    /**
     * The right to invoke `fd_seek`. This flag implies `rights::fd_tell`.
     *
     * - Bit: 2
     */
    fd_seek: rights(1n << 2n),

    /**
     * The right to invoke `fd_fdstat_set_flags`.
     *
     * - Bit: 3
     */
    fd_fdstat_set_flags: rights(1n << 3n),

    /**
     * The right to invoke `fd_sync`. If `path_open` is set, includes the right
     * to invoke `path_open` with `fdflags::rsync` and `fdflags::dsync`.
     *
     * - Bit: 4
     */
    fd_sync: rights(1n << 4n),

    /**
     * The right to invoke `fd_seek` in such a way that the file offset remains
     * unaltered (i.e., `whence::cur` with offset zero), or to invoke `fd_tell`.
     *
     * - Bit: 5
     */
    fd_tell: rights(1n << 5n),

    /**
     * The right to invoke `fd_write` and `sock_send`. If `rights::fd_seek` is
     * set, includes the right to invoke `fd_pwrite`.
     *
     * - Bit: 6
     */
    fd_write: rights(1n << 6n),

    /**
     * The right to invoke `fd_advise`.
     *
     * - Bit: 7
     */
    fd_advise: rights(1n << 7n),

    /**
     * The right to invoke `fd_allocate`.
     *
     * - Bit: 8
     */
    fd_allocate: rights(1n << 8n),

    /**
     * The right to invoke `path_create_directory`.
     *
     * - Bit: 9
     */
    path_create_directory: rights(1n << 9n),

    /**
     * If `path_open` is set, the right to invoke `path_open` with
     * `oflags::creat`.
     *
     * - Bit: 10
     */
    path_create_file: rights(1n << 10n),

    /**
     * The right to invoke `path_link` with the file descriptor as the source
     * directory.
     *
     * - Bit: 11
     */
    path_link_source: rights(1n << 11n),

    /**
     * The right to invoke `path_link` with the file descriptor as the target
     * directory.
     *
     * - Bit: 12
     */
    path_link_target: rights(1n << 12n),

    /**
     * The right to invoke `path_open`.
     *
     * - Bit: 13
     */
    path_open: rights(1n << 13n),

    /**
     * The right to invoke `fd_readdir`.
     *
     * - Bit: 14
     */
    fd_readdir: rights(1n << 14n),

    /**
     * The right to invoke `path_readlink`.
     *
     * - BIt: 15
     */
    path_readlink: rights(1n << 15n),

    /**
     * The right to invoke `path_rename` with the file descriptor as the source
     * directory.
     *
     * - Bit: 16
     */
    path_rename_source: rights(1n << 16n),

    /**
     * The right to invoke `path_rename` with the file descriptor as the target
     * directory.
     *
     * - Bit: 17
     */
    path_rename_target: rights(1n << 17n),

    /**
     * The right to invoke `path_filestat_get`.
     *
     * - Bit: 18
     */
    path_filestat_get: rights(1n << 18n),

    /**
     * The right to change a file's size. If `path_open` is set, includes the
     * right to invoke `path_open` with `oflags::trunc`. Note: there is no
     * function named `path_filestat_set_size`. This follows POSIX design, which
     * only has `ftruncate` and does not provide `ftruncateat`. While such
     * function would be desirable from the API design perspective, there are
     * virtually no use cases for it since no code written for POSIX systems
     * would use it. Moreover, implementing it would require multiple syscalls,
     * leading to inferior performance.
     *
     * - Bit: 19
     */
    path_filestat_set_size: rights(1n << 19n),

    /**
     * The right to invoke `path_filestat_set_times`.
     *
     * - Bit: 20
     */
    path_filestat_set_times: rights(1n << 20n),

    /**
     * The right to invoke `fd_filestat_get`.
     *
     * - Bit: 21
     */
    fd_filestat_get: rights(1n << 21n),

    /**
     * The right to invoke fd_filestat_set_size.
     *
     * - Bit: 22
     */
    fd_filestat_set_size: rights(1n << 22n),

    /**
     * The right to invoke `fd_filestat_set_times`.
     *
     * - Bit: 23
     */
    fd_filestat_set_times: rights(1n << 23n),

    /**
     * The right to invoke `path_symlink`.
     *
     * - Bit: 24
     */
    path_symlink: rights(1n << 24n),

    /**
     * The right to invoke `path_remove_directory`.
     *
     * - Bit: 25
     */
    path_remove_directory: rights(1n << 25n),

    /**
     * The right to invoke `path_unlink_file`.
     *
     * - Bit: 26
     */
    path_unlink_file: rights(1n << 26n),

    /**
     * If `rights::fd_read` is set, includes the right to invoke `poll_oneoff`
     * to subscribe to `eventtype::fd_read`. If `rights::fd_write` is set,
     * includes the right to invoke `poll_oneoff` to subscribe to
     * `eventtype::fd_write`.
     *
     * - Bit: 27
     */
    poll_fd_readwrite: rights(1n << 27n),

    /**
     * The right to invoke `sock_shutdown`.
     *
     * - Bit: 28
     */
    sock_shutdown: rights(1n << 28n),

    /**
     * The right to invoke `sock_accept`.
     *
     * - Bit: 29
     */
    sock_accept: rights(1n << 29n),
  },
);
