import { Brand } from "@askua/core/brand";

/**
 * U8
 */
export type U8 = number;

/**
 * Pointer
 */
export type Pointer<_> = number;

/**
 * size: u32
 */
export type Size = Brand<number, "wasi_snapshot_preview1.size">;
export const Size = Brand<number, "wasi_snapshot_preview1.size">;

/**
 * timestamp: u64
 *
 * Timestamp in nanoseconds.
 */
export type Timestamp = Brand<number, "wasi_snapshot_preview1.timestamp">;
export const Timestamp = Brand<number, "wasi_snapshot_preview1.timestamp">;

const clockid = Brand<number, "wasi_snapshot_preview1.clockid">;

/**
 * clockid: Variant
 *
 * Identifiers for clocks.
 */
export type Clockid = Brand<number, "wasi_snapshot_preview1.clockid">;
export const Clockid = Object.assign(
  clockid,
  {
    /**
     * The clock measuring real time. Time value zero corresponds with
     * 1970-01-01T00:00:00Z.
     */
    realtime: clockid(0),

    /**
     * The store-wide monotonic clock, which is defined as a clock measuring
     * real time, whose value cannot be adjusted and which cannot have negative
     * clock jumps. The epoch of this clock is undefined. The absolute time
     * value of this clock therefore has no meaning.
     */
    monotonic: clockid(1),

    /**
     * The CPU-time clock associated with the current process.
     */
    process_cputime_id: clockid(2),

    /**
     * The CPU-time clock associated with the current thread.
     */
    thread_cputime_id: clockid(3),
  },
);

/**
 * exitcode: u32
 *
 * Exit code generated by a process when exiting.
 */
export type Exitcode = Brand<number, "wasi_snapshot_preview1.exitcode">;
export const Exitcode = Brand<number, "wasi_snapshot_preview1.exitcode">;

const errno = Brand<number, "wasi_snapshot_preview1.errno">;

/**
 * errno: Variant
 *
 * Error codes returned by functions. Not all of these error codes are returned
 * by the functions provided by this API; some are used in higher-level library
 * layers, and others are provided merely for alignment with POSIX.
 */
export type Errno = Brand<number, "wasi_snapshot_preview1.errno">;
export const Errno = Object.assign(
  errno,
  {
    // No error occurred. System call completed successfully.
    success: errno(0),

    // Argument list too long.
    toobig: errno(1),

    // Permission denied.
    acces: errno(2),

    // Address in use.
    addrinuse: errno(3),

    // Address not available.
    addrnotavail: errno(4),

    // Address family not supported.
    afnosupport: errno(5),

    // Resource unavailable, or operation would block.
    again: errno(6),

    // Connection already in progress.
    already: errno(7),

    // Bad file descriptor.
    badf: errno(8),

    // Bad message.
    badmsg: errno(9),

    // Device or resource busy.
    busy: errno(0),

    // Operation canceled.
    canceled: errno(1),

    // No child processes.
    child: errno(2),

    // Connection aborted.
    connaborted: errno(3),

    // connrefused Connection refused.
    connrefused: errno(4),

    // connreset Connection reset.
    connreset: errno(5),

    // Resource deadlock would occur.
    deadlk: errno(6),

    // Destination address required.
    destaddrreq: errno(7),

    // Mathematics argument out of domain of function.
    dom: errno(8),

    // Reserved.
    dquot: errno(9),

    // File exists.
    exist: errno(0),

    // Bad address.
    fault: errno(1),

    // File too large.
    fbig: errno(2),

    // Host is unreachable.
    hostunreach: errno(3),

    // Identifier removed.
    idrm: errno(4),

    // Illegal byte sequence.
    ilseq: errno(5),

    // Operation in progress.
    inprogress: errno(6),

    // Interrupted function.
    intr: errno(7),

    // Invalid argument.
    inval: errno(8),

    // I/O error.
    io: errno(9),

    // Socket is connected.
    isconn: errno(0),

    // Is a directory.
    isdir: errno(1),

    // Too many levels of symbolic links.
    loop: errno(2),

    // File descriptor value too large.
    mfile: errno(3),

    // Too many links.
    mlink: errno(4),

    // Message too large.
    msgsize: errno(5),

    // Reserved.
    multihop: errno(6),

    // Filename too long.
    nametoolong: errno(7),

    // Network is down.
    netdown: errno(8),

    // Connection aborted by network.
    netreset: errno(9),

    // Network unreachable.
    netunreach: errno(0),

    // Too many files open in system.
    nfile: errno(1),

    // No buffer space available.
    nobufs: errno(2),

    // No such device.
    nodev: errno(3),

    // No such file or directory.
    noent: errno(4),

    // Executable file format error.
    noexec: errno(5),

    // No locks available.
    nolck: errno(6),

    // Reserved.
    nolink: errno(7),

    // Not enough space.
    nomem: errno(8),

    // No message of the desired type.
    nomsg: errno(9),

    // Protocol not available.
    noprotoopt: errno(0),

    // No space left on device.
    nospc: errno(1),

    // Function not supported.
    nosys: errno(2),

    // The socket is not connected.
    notconn: errno(3),

    // Not a directory or a symbolic link to a directory.
    notdir: errno(4),

    // Directory not empty.
    notempty: errno(5),

    // State not recoverable.
    Notrecoverable: errno(6),

    // Not a socket.
    notsock: errno(7),

    // Not supported, or operation not supported on socket.
    notsup: errno(8),

    // Inappropriate I/O control operation.
    notty: errno(9),

    // No such device or address.
    nxio: errno(0),

    // Value too large to be stored in data type.
    overflow: errno(1),

    // Previous owner died.
    ownerdead: errno(2),

    // Operation not permitted.
    perm: errno(3),

    // Broken pipe.
    pipe: errno(4),

    // Protocol error.
    proto: errno(5),

    // Protocol not supported.
    protonosupport: errno(6),

    // Protocol wrong type for socket.
    prototypes: errno(7),

    // Result too large.
    range: errno(8),

    // Read-only file system.
    rofs: errno(9),

    // Invalid seek.
    spipe: errno(0),

    // No such process.
    srch: errno(1),

    // Reserved.
    stale: errno(2),

    // Connection timed out.
    timedout: errno(3),

    // Text file busy.
    txtbsy: errno(4),

    // Cross-device link.
    xdev: errno(5),

    // Extension: Capabilities insufficient.
    notcapable: errno(6),
  },
);

/**
 * fd: Handle
 *
 * A file descriptor handle.
 */
export type Fd = Brand<number, "wasi_snapshot_preview1.fd">;
export const Fd = Brand<number, "wasi_snapshot_preview1.fd">;

/**
 * ciovec: Record
 *
 * A region of memory for scatter/gather writes.
 *
 * - Size: 8
 * - Alignment: 4
 *
 * ## Record members
 *
 * - buf: ConstPointer<u8> The address of the buffer to be written.
 *   - Offset: 0
 * - buf_len: size The length of the buffer to be written.
 *   - Offset: 4
 */
export type Ciovec = Brand<never, "wasi_snapshot_preview1.ciovec">;

/**
 * subscription: Record
 *
 * Subscription to an event.
 *
 * - Size: 48
 * - Alignment: 8
 *
 * ## Record members
 *
 * - userdata: [userdata] User-provided value that is attached to the
 *   subscription in the implementation and returned through [event::userdata].
 *   - Offset: 0
 * - u: [subscription_u] The type of the event to which to subscribe, and its
 *   contents
 *   - Offset: 8
 */
export type Subscription = Brand<never, "wasi_snapshot_preview1.subscription">;

/**
 * event: Record
 *
 * An event that occurred.
 *
 * - Size: 32
 * - Alignment: 8
 *
 * ## Record members
 *
 * - userdata: userdata User-provided value that got attached to
 *   subscription::userdata.
 *   - Offset: 0
 * - error: errno If non-zero, an error that occurred while processing the
 *   subscription request.
 *   - Offset: 8
 * - type: eventtype The type of event that occured
 *   - Offset: 10
 * - fd_readwrite: event_fd_readwrite The contents of the event, if it is an
 *   eventtype::fd_read or eventtype::fd_write. eventtype::clock events ignore this field.
 *   - Offset: 16
 */
export type Event = Brand<never, "wasi_snapshot_preview1.event">;

const fdflags = Brand<number, "wasi_snapshot_preview1.fdflags">;

/**
 * File descriptor flags.
 */
export type Fdflags = Brand<number, "wasi_snapshot_preview1.fdflags">;
export const Fdflags = Object.assign(
  fdflags,
  {
    /**
     * bool Append mode: Data written to the file is always appended to
     * the file's end.
     * - Bit: 0
     */
    append: fdflags(1),

    /**
     * bool Write according to synchronized I/O data integrity
     * completion. Only the data stored in the file is synchronized.
     * - Bit: 1
     */
    dsync: fdflags(2),

    /**
     * bool Non-blocking mode.
     * - Bit: 2
     */
    nonblock: fdflags(4),

    /**
     * bool Synchronized read I/O operations.
     * - Bit: 3
     */
    rsync: fdflags(8),

    /**
     * bool Write according to synchronized I/O file integrity completion.
     * In addition to synchronizing the data stored in the file, the
     * implementation may also synchronously update the file's metadata.
     * - Bit: 4
     */
    sync: fdflags(16),
  },
);

/**
 * fdstat: Record
 *
 * File descriptor attributes.
 *
 * - Size: 24
 * - Alignment: 8
 *
 * ## Record members
 *
 * - fs_filetype: filetype File type.
 *   - Offset: 0
 * - fs_flags: fdflags File descriptor flags.
 *   - Offset: 2
 * - fs_rights_base: rights Rights that apply to this file descriptor.
 *   - Offset: 8
 * - fs_rights_inheriting: rights Maximum set of rights that may be installed on
 *   new file descriptors that are created through this file descriptor, e.g.,
 *   through path_open.
 *   - Offset: 16
 */
export type Fdstat = Brand<never, "wasi_snapshot_preview1.fdstat">;

/**
 * prestat: Variant
 *
 * Information about a pre-opened capability.
 *
 * - Size: 8
 * - Alignment: 4
 *
 * ## Variant Layout
 *
 * - size: 8
 * - align: 4
 * - tag_size: 1
 *
 * ## Variant cases
 *
 * - dir: prestat_dir
 */
export type Prestat = Brand<never, "wasi_snapshot_preview1.prestat">;
